import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/StyledComponents";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const KAKAO_APP_KEY = process.env.NEXT_PUBLIC_KAKAO_JS_KEY;

  return (
    <html lang="en">
      <head>
        <title>정주❤️유리 결혼합니다</title>
      </head>
      <body className={inter.className}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        <div id="react-modals" />
      </body>
    </html>
  );
}
